require 'rubygems'
require 'echoe'
require 'release'

Echoe.new("ruby-libgearman") do |p|
  p.author = "Monty Taylor"
	p.email = "mordred@inaugust.com"
  p.project = "ruby-libgearman"
  p.version = LibgearmanRelease::version
  p.summary = "An interface to the libgearman C client."
  p.description = "These are the ruby wrappers for libgearman which can be used to provide Gearman Workers and to connect as Gearman Clients."
  p.url = "http://launchpad.net/gearman-interface"
  p.ignore_pattern = "release.rb.in"
end
